name: city_pickers
description:  Flutter plugin for city picker,  Popups widgets, call by function,  support china.
version: 0.1.29
author: sanfan.hx<sanfan.hx@alibaba-inc.com>
homepage: https://github.com/hanxu317317/city_pickers

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lpinyin: ^1.0.7

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
